DUEditor/urls.py
#coding:utf-8
'''
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import url
else:
    from django.conf.urls.defaults import patterns, url


'''

from django.conf.urls import url
from .views import get_ueditor_controller
urlpatterns = [
    url(r'^controller/$',get_ueditor_controller),
]

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('<int:year>/<int:month>/<int:day>/<slug:post>/',
    #      views.post_detail,
    #      name='post_detail'),
    path('article/<slug:slug>', views.post_detail, name='post_detail'),
    # 这里的参数类型不要写slug，否则又会忽视中文，写str就行了
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostFeed(), name='post_feed'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import blog_index, post_search
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf.urls.static import static
from django.conf import settings

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('', blog_index, name='index'),
    path('search/', post_search, name='post_search'),
    path('admin/', admin.site.urls),
    path('ueditor/', include('DUEditor.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from DUEditor.models import UEditorField
from taggit.managers import TaggableManager
from taggit.models import TagBase, GenericTaggedItemBase
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext, gettext_lazy as _
import uuslug


class MyTag(TagBase):
    # 这一步是关键 要设置allow_unicode=True 这样这个字段才能支持中文
    slug = models.SlugField(verbose_name=_("slug"), unique=True, max_length=100, allow_unicode=True)

    # 这个方法也是要覆盖的，它是用来计算slug的，也是添加allow_unicode=True参数
    def slugify(self, tag, i=None):
        slug = slugify(tag, allow_unicode=True)
        if i is not None:
            slug += "_%d" % i
        return slug

    class Meta:
        verbose_name = _("tag")
        verbose_name_plural = _("tags")
        app_label = "taggit"


class TaggedWhatever(GenericTaggedItemBase):
    # 把我们自定义的模型传递进来，它就能知道如何处理
    tag = models.ForeignKey(
        MyTag,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'))
    title = models.CharField(max_length=250, verbose_name='文章标题')
    slug = models.SlugField(verbose_name="别名", max_length=250, null=True, blank=True)
    category = models.ForeignKey('PostCategory', on_delete=models.SET_NULL, null=True)
    tags = TaggableManager(through=TaggedWhatever)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', verbose_name='作者')
    thumbnail = models.URLField(verbose_name="封面链接", null=True, blank=True)
    desc = models.CharField(max_length=200, verbose_name="摘要", null=True, blank=True)
    body = UEditorField(verbose_name='文章内容', width=960, height=600)
    publish = models.DateTimeField(default=timezone.now, verbose_name='发布时间')
    created = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft', verbose_name='文章状态')

    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = uuslug.slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class PostCategory(models.Model):
    name = models.CharField(max_length=100, verbose_name="分类")

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Banner(models.Model):
    name = models.CharField(max_length=200, verbose_name="幻灯片名称")
    priority = models.IntegerField(default=0, verbose_name="优先级")
    image_url = models.URLField(verbose_name="图片地址")
    link_to = models.URLField(verbose_name="跳转链接")
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = '幻灯片'
        verbose_name_plural = verbose_name
        ordering = ['-priority']

blog/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(label="请输入搜索关键字")

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from .models import Post, MyTag, Banner
from .forms import SearchForm
from django.db.models import Q



def blog_index(request):
    objects = Post.published.all()
    posts = objects[:5]
    banners = Banner.objects.all()
    return render(request, 'blog/index.html', {'posts': posts, 'banners': banners})


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        # 从MyTag对应的数据库表里查询tag
        tag = get_object_or_404(MyTag, slug=tag_slug)
        # 因为文章和标签是多对多的关系，所以这里要把tag放到列表里面
        # 这里的意思是查询那些文章标签里包含给定标签的文章
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 5)  # 每页5篇文章
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug,
                             status='published')
    # post_tags_ids = post.tags.values_list('id', flat=True)
    # similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    # similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/detail.html', {'post': post,
                                                # 'similar_posts': similar_posts,
                                                })


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    context = {}
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.filter(Q(title__contains=query)|Q(body__contains=query))
            paginator = Paginator(results, 5)  # 每页5篇文章
            page = request.GET.get('page')
            try:
                posts = paginator.page(page)
            except PageNotAnInteger:
                posts = paginator.page(1)
            except EmptyPage:
                posts = paginator.page(paginator.num_pages)
            context['posts'] = posts
            context['page'] = page
            context['query'] = query
    return render(request, 'blog/search.html', context=context)

blog/templates/simple/post/detail.html
{% extends 'blog/base.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block head %}
    <link href="{% static 'js/SyntaxHighlighter/shCoreDefault.css' %}" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="{% static 'js/SyntaxHighlighter/shCore.js' %}"></script>
    <script>
        SyntaxHighlighter.all();//执行代码高亮
    </script>
{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        发布时间: {{ post.publish }} 作者: {{ post.author }}
    </p>
    {{ post.body|safe }}
    <h2>相关文章</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        暂时没有相关文章
    {% endfor %}

{% endblock %}

blog/templates/simple/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/simple/post/list.html
{% extends 'blog/base.html' %}
{% block title %}
    博客列表
{% endblock %}
{% block content %}
    <h1>Python Lover</h1>
    {% if tag %}
        <h2>匹配标签 "{{ tag.name }}" 的文章:</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="tags">标签:
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}

        </p>
        <p class="date">
        发布时间: {{ post.publish }} 作者: {{ post.author }}
        </p>
    {% endfor %}
    {% include 'pagination.html' with page=posts %}
{% endblock %}

blog/templates/simple/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}
    搜索
{% endblock %}
{% block content %}
    {% if query %}
        <h1>包含 "{{ query }}" 的文章</h1>
        <h3>
            {% with results.count as total_results %}
                共查找到 {{ total_results }} 篇文章
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {% empty %}
            <p>未查询到相关文章</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">再次搜索</a></p>
    {% else %}
        <h1>搜索文章</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="搜索">
        </form>
    {% endif %}
{% endblock %}